name: agdc
dependencies:
- python=2.7
- pyyaml
- sqlalchemy
- python-dateutil
- jsonschema
- cachetools
- numpy
- numexpr
- rasterio >=0.34
- singledispatch
- netcdf4
- psycopg2
- gdal >=1.9
- dask
- xarray
- pylint # testing
- pep8 # testing
- fiona # movie generator app
- mock # testing
- hypothesis # testing
- matplotlib # pixel drill app
- pip:
  - pypeg2
  - pytest-cov # testing
  - pathlib
  - pytest-logging
  - pytest-faulthandler
