build: false

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\.appveyor\\run_with_env.cmd"

  PGUSER: postgres
  PGPASSWORD: Password12!
  POSTGRES: C:\Program Files\PostgreSQL\9.5\bin\


  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python

#    - MINICONDA: C:\\Miniconda-x64
#      PYTHON_VERSION: 27
#      PYTHON_ARCH: 32
    - MINICONDA: C:\\Miniconda35-x64
      PYTHON_VERSION: 35
#      PYTHON_ARCH: 64

services:
  - postgresql

init:
  - ECHO %PYTHON% %PGUSER% %PGPASSWORD%

  - set PATH=%MINICONDA%;%MINICONDA%\Scripts;%POSTGRES%;%PATH%

install:
  - SET
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "System Path"
  - ps: $env:Path

  - ECHO "Local Path"
  - ps: ls

  - conda config --prepend channels conda-forge
  - conda config --show-sources
  - conda config --show
  - conda update --all -y
  - conda env create -n agdc --file .appveyor\environment_py%PYTHON_VERSION%.yaml
  - activate agdc


before_test:
  - createdb agdcintegration
  # Print a bunch of useful information
  - pip --version
  - python --version
  - pylint --version
  - pep8 --version
  - py.test --version
  - conda --version
  - cd
  - dir
  - psql -c "SELECT current_setting('TIMEZONE');"
  - systeminfo
  - conda env export

test_script:
  - pep8 tests integration_tests --max-line-length 120

  - pylint -j 4 --reports no datacube datacube_apps

  # Run tests, save coverage and test results
  - py.test --junit-xml=junit-results.xml --cov datacube --durations=5 datacube datacube_apps tests integration_tests

  # upload results to AppVeyor
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: '$wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path
  .\junit-results.xml))'
